# Generated by Django 4.0.6 on 2022-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpermission',
            name='email',
            field=models.EmailField(default=160, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestpermission',
            name='name',
            field=models.CharField(default=1160, max_length=30),
            preserve_default=False,
        ),
    ]
