# Generated by Django 4.0.6 on 2022-07-25 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling', '0002_requestpermission_email_requestpermission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='RequestUser', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
