# Generated by Django 4.0.6 on 2022-07-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_remove_requestpermission_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpermission',
            name='name',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
