# Generated by Django 4.0.6 on 2022-08-01 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling', '0005_requestpermission_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('date_save', models.DateTimeField(auto_now_add=True)),
                ('inspect_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspect_user', to=settings.AUTH_USER_MODEL)),
                ('label_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
