# Generated by Django 4.0.6 on 2022-08-01 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling', '0006_initialimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialimage',
            name='inspect_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspect_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initialimage',
            name='label_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
