# Generated by Django 4.0.6 on 2022-08-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_alter_initialimage_inspect_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialimage',
            options={'ordering': ['-id']},
        ),
    ]
