# Generated by Django 4.0.6 on 2022-08-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0009_alter_initialimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_or_model', models.BooleanField(default=True)),
                ('date_classification', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labeling.initialimage')),
            ],
        ),
    ]
