# Generated by Django 4.0.6 on 2022-08-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0010_classificationimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationimage',
            old_name='detail_or_model',
            new_name='detail_or_not',
        ),
    ]
